### ISSUE TITLE
Replace underscores for dashs in multi word names

### ISSUE THREAD

**Issue by alexjp** [jeregrine/jsonapi#12]
Seems that according to jsonapi spec and ember data jsonapi,

some_thing , should become some-thing.

In the jsonapi.org page, it has the example:
....

```
attributes": {
      "first-name": "Dan",
      "last-name": "Gebhardt",
      "twitter": "dgeb"
    },
```

....

If i manage to learn how to do this, i can do it on the weekend and write some tests.

**Comment by jeregrine** [comment]
@alexjp nice. A hint is we could process the attributes here https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi.ex#L86 maybe piping it into a new function.

**Comment by adamesque** [comment]
Important to note that JSONAPI recommends using dashes, but does not require them. An easy way to opt-in to dasherized attributes would be great though!

**Comment by yordis** [comment]
@alexjp @adamesque in the spec doesn't say anything about any recommendation in term of naming. Correct me if I am wrong http://jsonapi.org/format/#document-member-names

> To enable an easy mapping of member names to URLs, it is RECOMMENDED that **member names use only non-reserved**, URL safe characters specified in RFC 3986.

Either way, API consumers most of the time will prefer to have underscore instead of dashes, the dot notation is broken when you use dashes. `.attributes.first_name` vs (Hopefully) `.attributes['first-name']` 

@alexjp in the Ember examples they use underscore as well http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_using-json-api-error-object-format

This could be a extra configuration to add but I wouldn't recommend to put it by default

**Comment by emwalker** [comment]
The latest version of the spec [recommends hyphen minus](http://jsonapi.org/recommendations/) as a separator between multiple words.

**Comment by yordis** [comment]
@emwalker yep, R.I.P Javascript dot notation with it or anyone that can read it with `dot` notation or R.I.P languages that don't support `dashes` in the hash keys.

**Comment by doomspork** [comment]
@jeregrine do we want to support this change by default or add a configuration option to swap `_` for `-`?  I can take a stab at getting a PR up for this.

**Comment by jeregrine** [comment]
I have no strong convictions on this one @doomspork configuration may be best. Or maybe a function?
