### ISSUE TITLE
Relationships to not require a View specified

### ISSUE THREAD

**Issue by snewcomer** [jeregrine/jsonapi#78]
## Potential Issue

Currently it seems a `view` is required to process any type of relationship.

```
ticket_view.ex

def relationships, do: [ticket_categories: MyProject.TicketCategoryView]
```

Right now, the below is needed because [encode_data](https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/serializer.ex#L38) is called recursively through all the relationships and asks for each relationships `view`.
```
ticket_category_view.ex

def relationships, do: [category: MyProject.CategoryView, ticket: MyProject.TicketView]
```

example payload
```
{
  "relationships": {
    "ticket-categories": {
      "data": [{"id": "1234", "type": "ticket-category"}]
    }
  }
}
```

## Brainstorming a solution

Since I'm most likely missing something, the first step for me would be to understand the need for a relationship's `view`.  In this case, it seems what might be ok to do is something like. 

`[ticket_categories: %{type: "ticket-category", field: "ticket_category_id"}]`

Then one option during serialization of the data would have the lib do `Map.get(ticket_data, field)` to get the `id` for the relationship instead of recursively moving down the relationship tree.

Would appreciate some thoughts.  I would love to open a PR!

**Comment by jeregrine** [comment]
@snewcomer

History: The reason I require a view is because it allows the user to define an id callback on their view to define their own id's. Otherwise the default is to just pull the id from the model. https://github.com/jeregrine/jsonapi/blob/master/lib/jsonapi/view.ex#L83-L85 I try to provide smart defaults and allow almost anything to be overridden. 

In Phoenix view's are just Modules and functions, creating a bunch of views doesn't end up creating a bunch of overhead. 

I'm not sure I understand the problem enough to comment on your proposal though. It seems like you could just create a View and it would just work?

**Comment by jeregrine** [comment]
Also @snewcomer your proposal would never allow the relationship to be included as it wouldn't know how to render it.

**Comment by snewcomer** [comment]
Yep I think I am wrong here.  Thanks for the explanation!

Doing some perf testing with benchee so will see if I find anything.

**Comment by jeregrine** [comment]
Thanks @snewcomer! Lemme know if have any questions or if you have pr's to make your life easier I'll gladly accept.
